config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :users do
    resources :questions do
      resources :answers
    end
  end
  resource :sessions
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :question_id, :user_id, :body, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :user_id, :title, :body, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  validates :email, :password, :username, :presence => true
  validates_confirmation_of :password
  validates_uniqueness_of :email
  before_save :encrypt_password
  after_create :send_signup_confirmation
  has_many :questions
  has_many :answers

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def send_signup_confirmation
    UserMailer.signup_confirmation(self).deliver_now
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @answer.question_id = @question.id
    if @answer.save
      flash[:notice] = "Your answer has been posted"
      redirect_to user_question_path(current_user, @question)
    else
      flash[:alert] = "Something went wrong. You idiot."
      render :new
    end
  end

  def show
    @answer = current_user.answers.find(params[:id])
    @question = Question.find(params[:question_id])
  end


  private

  def answer_params
    params.require(:answer).permit(:body)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Your question has been posted"
      redirect_to user_question_path(current_user, @question)
    else
      flash[:alert] = "Something went wrong. You idiot."
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def index
    @questions = Question.all
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in"
      session[:user_id] = @user.id
      redirect_to user_questions_path(@user)
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to new_sessions_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Stack Overflow. Please enter your email and password"
      redirect_to new_sessions_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
  end

  def destroy
  end

  def update
  end

  def edit
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<h1>Contribute An Answer</h1>
<%= form_for [current_user, @question, Answer.new] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <% if current_user.present? %>
    <%= link_to current_user.username, user_path(current_user) %>
    <%= link_to "Log Out", sessions_path, method: :delete %> <!-- calling sessions_path in order to destroy -->
    <% else %>
    <%= link_to "Log In", new_sessions_path %>
    <%= link_to "Sign Up", new_user_path %>
    <% end %>

  </header>

<%= flash[:notice] %>
<%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>Top Questions</h1>

<ul>
  <% @questions.each do |question| %>
  <li>
    <%= link_to question.title, user_question_path(question.user, question) %>
  </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>new question</h1>
<%= form_for [current_user, Question.new] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<p>
  <%= @question.body %>
</p>

<%= link_to "Add An Answer", new_user_question_answer_path(current_user, @question) %>

<% if @answers.any? %>
  <ul>
    <% @answers.each do |answer| %>
      <li> <%= answer.body %> </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no answers</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=form_for User.new do |f| %>
<%=f.label :username %>
<%=f.text_field :username %>
<%=f.label :email %>
<%=f.text_field :email %>
<%=f.label :password %>
<%=f.password_field :password %>
<%=f.label :password_confirmation %>
<%=f.password_field :password_confirmation %>
<%=f.submit "Sign Up" %>
<%end%>

app/views/users/show.html.erb
<h1>Welcome</h1>
<%= current_user.email %>
<%= link_to "New Question", new_user_question_path(current_user) %>
<h2>Your questions</h2>
<% if current_user.questions.any? %>
  <ul>
    <% current_user.questions.each do |question| %>
      <li> <%= link_to question.title, user_question_path(current_user, question) %> </li>
    <% end %>
  </ul>
<% end %>